export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLES = "GET_ARTICLES";
export const ARTICLE_LOADING = "ARTICLE_LOADING";
export const ARTICLE_NOT_FOUND = "ARTICLE_NOT_FOUND";
export const CLEAR_CURRENT_ARTICLE = "CLEAR_CURRENT_ARTICLE";
